package com.hawolt.client.resources.ledge.store.objects;

/**
 * Created: 28/07/2023 01:52
 * Author: Twitter @hawolt
 **/

public enum InventoryType {
    AUGMENT_SLOT,
    SPELL_BOOK_PAGE,
    BUNDLES,
    BOOST,
    MYSTERY,
    TOURNAMENT_FLAG,
    COMPANION,
    GIFT,
    SUMMONER_CUSTOMIZATION,
    QUEUE_ENTRY,
    CHAMPION,
    TRANSFER,
    CHAMPION_SKIN,
    TFT_DAMAGE_SKIN,
    CURRENCY,
    SUMMONER_ICON,
    EVENT_PASS,
    STATSTONE,
    EMOTE,
    TOURNAMENT_TROPHY,
    TEAM_SKIN_PURCHASE,
    MODE_PROGRESSION_REWARD,
    WARD_SKIN,
    HEXTECH_CRAFTING,
    TFT_MAP_SKIN,
    AUGMENT,
    RP,
    TOURNAMENT_FRAME,
    REGALIA_CREST,
    REGALIA_BANNER,
    TFT_PLAYBOOK,
    TOURNAMENT_LOGO,
    ACHIEVEMENT_TITLE
}
